version: '3.7'

services:
  db:
    image: postgres
    container_name: django_tenants_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_USER=django_tenants
      - POSTGRES_PASSWORD=django_tenants
      - POSTGRES_DB=django_tenants
      - DATABASE_PORT=5433
    ports:
      - "5433:5432"
  web:
    build: .
    command: bash -c "cd app/ && python manage.py runserver 0.0.0.0:8000"
    container_name: django_tenants_web
    volumes:
      - .:/code:z
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_USER=django_tenants
      - DATABASE_PASSWORD=django_tenants
      - DATABASE_DB=django_tenants
      - DATABASE_HOST=db

  django-tenants-pgadmin:
    container_name: django_tenants_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  redis:
    image: redis:6.0.10
    ports:
      - "6379:6379"